### ISSUE TITLE
Move existing assets from Google Drive to Github

### ISSUE THREAD

**Issue by t-karcher** [ChrisOKay/AztecChallenge#1]
Sprites, Screenshots, ... everything. It's probably a good idea to create a separate "assets" subfolder within the game folder first.

**Comment by ChrisOKay** [comment]
is this good practice in godot as well? "The one" folder structure I found kept any non-godot-imported stuff (raw sounds, etc.) in the root folder below the game folder. I'll go this way first, but if you don't like it, we can move it into the game folder.

**Comment by t-karcher** [comment]
Sounds like a good idea - no objections from my side. 
Note to self: Check out some other Godot game repositories for best practices.
