### ISSUE TITLE
Use the built-in physics engine to reproduce the original side scrolling effect

### ISSUE THREAD

**Issue by t-karcher** [ChrisOKay/AztecChallenge#2]
I just thought about how to (ab-)use the Godot physics engine to reproduce the side scrolling of the original Aztec game. Here's what I came up with: Set the surface friction to zero (think of totally icy ground), "push" the sprite at the start of the level, and let him lose a life / restart the level once the forward movement is stopped by the first obstacle.

**Comment by t-karcher** [comment]
Status update regarding using the built-in physics engine:
So far, so good: Sprite is animated, is falling, and is colliding with the ground. And all of this without a single line of code.
Enough for today.

**Comment by ChrisOKay** [comment]
👍  good start, good start. Icy push sounds reasonable as well.

**Comment by t-karcher** [comment]
Test completed, and works as expected: A frictionless ground, a camera attached to the player and a single line of code during initialization of the player (`set_axis_velocity(Vector2(100,0))`) is enough to create the desired effect. (run Node2D.tscn in branch anim-test to see what I've done)
