### ISSUE TITLE
Add repository description

### ISSUE THREAD

**Issue by t-karcher** [ChrisOKay/AztecChallenge#28]
There should be an "edit" link next to the missing description on the code page, but apparently it's only visible for the repository owner.

**Comment by t-karcher** [comment]
I was thinking more of something along the lines "Retro platformer inpired by Cosmis Atzec Challenge, implemented with the Godot game engine." but thanks anyway. :-)

**Comment by ChrisOKay** [comment]
I detect a slight offset of taking-things-seriously between the project partners. Maybe I should skip the creation of Hartmut Hähnchen....
