### ISSUE TITLE
Find fonts close to the ones used in the original game

### ISSUE THREAD

**Issue by t-karcher** [ChrisOKay/AztecChallenge#3]
**Menu options, Level names**
- http://de.fontriver.com/font/zelda_dx/

**Text "Phase",  "High Score"** /\* Probably not needed - we can as well just display a static image */
- http://de.fontriver.com/font/e4_2017/
- http://de.fontriver.com/font/blocko/

**Big numbers** /\* for scores etc */
- http://de.fontriver.com/font/moder_dos_437/
- http://de.fontriver.com/font/my_phone_n1280/
- http://de.fontriver.com/font/pc_senior/

**Comment by t-karcher** [comment]
@ChrisOKay : Since currently neither the design nor the sound (great sound effects, btw!) is close to the original, do we still need the fonts listed above? For now, I'll just continue to use the standard font. Feel free to close this issue and/or add the fonts you like to the project

**Comment by ChrisOKay** [comment]
@t-karcher If I find the time to work on the level & character design, I will include appropriate fonts.
