### ISSUE TITLE
Decide on number of levels

### ISSUE THREAD

**Issue by t-karcher** [ChrisOKay/AztecChallenge#8]
When searching for the missing jump sound, I came across this video:
https://www.youtube.com/watch?v=FDNpeKo_10g

First of all: This one does contain a couple of low jumps (yay!)

Second: It also contains a valuable comment describing the astonishing amount of levels!

> This game having 28 phases on 4 difficult levels. Each difficult leves having 7 screens:
> "The grounds","The columns","Grounds&Columns","Fire&caves","The batons","The gems"
> and "The tunnels". This game is very hard and having levels random generated. I couldn't
> pass by phase 24. Phase 8 is like phase 1 but the man run faster and level has random
> pieces shorter. Phase 12 having double batons moving up than phase 5 whick contain
> single batons moving up. After phase 21, the man don't allowed to jump too high because
> loose life as soon as hit be ceilling, not only that run too faster.﻿

I do remember the first three screens, but I think I never saw anything past "Grounds & Columns", let alone moving batons. Can we agree on implementing the first three screens only? Otherwise, we'd need to find more screenshots and videos for these higher phases...

**Comment by ChrisOKay** [comment]
First three screens are fine. This is just a first test, and I will pat myself on the shoulder if I do not destroy too much with wrong git pushes.
