### ISSUE TITLE
Original design vs. own design

### ISSUE THREAD

**Issue by t-karcher** [ChrisOKay/AztecChallenge#9]
While thinking about the copyright issues of using the original music, I also thought about the artwork: As with the music, using the original art in a public project like this one would violate Cosmis copyright. Yes, the risk of being prosecuted for that is probably minimal, but why risk it instead of using a licence-free [1] or own design instead? We'd still create a platformer game with all the features and mechanics we wanted to include, just without any copyright issues. What do you think?

[1] This one, for example: http://opengameart.org/content/platformer-art-complete-pack-often-updated

**Comment by ChrisOKay** [comment]
Sounds good. I don't like the thought of using out-of-the-box art, though. I'd like to create it by myself. I lack the time and expertise at the moment, but maybe we could use the pre-made stuff first and then replace it by something else later on.
